name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

      # Options
          # Base content
          base: header, activity, community, repositories, metadata
          # Core
          user: jiange1236
          template: classic
          config_display: large
          config_timezone: Asia/Shanghai
          # GitHub plugins
          plugin_achievements: yes
          plugin_activity: yes
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_lines: yes
          plugin_notable: yes
          plugin_repositories: yes
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          # Social plugins
          plugin_pagespeed: yes
